import AppKit
import Foundation

@MainActor
enum Paster {
    enum Outcome {
        case pasted
        case copiedOnly
    }

    private static let sessionType = NSPasteboard.PasteboardType("com.hugok94.magneto.session")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    static func deliver(_ text: String) async -> Outcome {
        let pasteboard = NSPasteboard.general
        let snapshot = snapshotItems(pasteboard)

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
        item.setData(Data(), forType: sessionType)
        pasteboard.writeObjects([item])

        guard Permissions.accessibilityGranted else {
            return .copiedOnly
        }

        try? await Task.sleep(for: .milliseconds(120))
        postCmdV()
        try? await Task.sleep(for: .milliseconds(600))

        restoreIfStillOwned(pasteboard, snapshot: snapshot)
        return .pasted
    }

    static func copyPlain(_ text: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    private static func snapshotItems(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        (pasteboard.pasteboardItems ?? []).compactMap { item in
            var entry: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types {
                if let data = item.data(forType: type) {
                    entry[type] = data
                }
            }
            return entry.isEmpty ? nil : entry
        }
    }

    /// Restores the previous clipboard only if our transcript is still on the
    /// pasteboard: if the user copied something in between, that copy wins.
    private static func restoreIfStillOwned(
        _ pasteboard: NSPasteboard,
        snapshot: [[NSPasteboard.PasteboardType: Data]]
    ) {
        guard !snapshot.isEmpty else { return }
        let stillOwned = pasteboard.pasteboardItems?.contains { $0.types.contains(sessionType) } ?? false
        guard stillOwned else { return }
        pasteboard.clearContents()
        let items = snapshot.map { entry -> NSPasteboardItem in
            let item = NSPasteboardItem()
            for (type, data) in entry {
                item.setData(data, forType: type)
            }
            return item
        }
        pasteboard.writeObjects(items)
    }

    /// Virtual key 9 is the physical V key, layout-independent (works on AZERTY).
    private static func postCmdV() {
        guard let source = CGEventSource(stateID: .privateState) else { return }
        let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: true)
        keyDown?.flags = .maskCommand
        let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 9, keyDown: false)
        keyUp?.flags = .maskCommand
        keyDown?.post(tap: .cghidEventTap)
        usleep(10_000)
        keyUp?.post(tap: .cghidEventTap)
    }
}
